# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'One_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProjectOne_MainWindow(object):
    def setupUi(self, ProjectOne_MainWindow):
        ProjectOne_MainWindow.setObjectName("ProjectOne_MainWindow")
        ProjectOne_MainWindow.resize(290, 295)
        ProjectOne_MainWindow.setMinimumSize(QtCore.QSize(290, 295))
        ProjectOne_MainWindow.setMaximumSize(QtCore.QSize(700, 500))
        self.centralwidget = QtWidgets.QWidget(ProjectOne_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.PowerOn_label = QtWidgets.QLabel(self.centralwidget)
        self.PowerOn_label.setGeometry(QtCore.QRect(10, 10, 121, 16))
        self.PowerOn_label.setObjectName("PowerOn_label")
        self.PowerOn_btn = QtWidgets.QPushButton(self.centralwidget)
        self.PowerOn_btn.setGeometry(QtCore.QRect(10, 30, 41, 31))
        self.PowerOn_btn.setObjectName("PowerOn_btn")
        self.Channels_label = QtWidgets.QLabel(self.centralwidget)
        self.Channels_label.setGeometry(QtCore.QRect(200, 120, 81, 20))
        self.Channels_label.setObjectName("Channels_label")
        self.ChannelDown_btn = QtWidgets.QPushButton(self.centralwidget)
        self.ChannelDown_btn.setGeometry(QtCore.QRect(220, 160, 51, 41))
        self.ChannelDown_btn.setObjectName("ChannelDown_btn")
        self.ChannelUp_btn = QtWidgets.QPushButton(self.centralwidget)
        self.ChannelUp_btn.setGeometry(QtCore.QRect(220, 70, 51, 41))
        self.ChannelUp_btn.setObjectName("ChannelUp_btn")
        self.Volume_label = QtWidgets.QLabel(self.centralwidget)
        self.Volume_label.setGeometry(QtCore.QRect(10, 120, 71, 16))
        self.Volume_label.setObjectName("Volume_label")
        self.VoluemDown_btn = QtWidgets.QPushButton(self.centralwidget)
        self.VoluemDown_btn.setGeometry(QtCore.QRect(10, 160, 51, 41))
        self.VoluemDown_btn.setObjectName("VoluemDown_btn")
        self.VolumeUp_btn = QtWidgets.QPushButton(self.centralwidget)
        self.VolumeUp_btn.setGeometry(QtCore.QRect(10, 70, 51, 41))
        self.VolumeUp_btn.setObjectName("VolumeUp_btn")
        self.Mute_label = QtWidgets.QLabel(self.centralwidget)
        self.Mute_label.setGeometry(QtCore.QRect(90, 90, 81, 16))
        self.Mute_label.setObjectName("Mute_label")
        self.MuteOn_btn = QtWidgets.QPushButton(self.centralwidget)
        self.MuteOn_btn.setGeometry(QtCore.QRect(90, 110, 41, 31))
        self.MuteOn_btn.setObjectName("MuteOn_btn")
        self.PowerOff_btn = QtWidgets.QPushButton(self.centralwidget)
        self.PowerOff_btn.setGeometry(QtCore.QRect(60, 30, 41, 31))
        self.PowerOff_btn.setObjectName("PowerOff_btn")
        self.MuteOff_btn = QtWidgets.QPushButton(self.centralwidget)
        self.MuteOff_btn.setGeometry(QtCore.QRect(140, 110, 41, 31))
        self.MuteOff_btn.setObjectName("MuteOff_btn")
        ProjectOne_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ProjectOne_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 290, 24))
        self.menubar.setObjectName("menubar")
        self.menuTelevision = QtWidgets.QMenu(self.menubar)
        self.menuTelevision.setObjectName("menuTelevision")
        ProjectOne_MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ProjectOne_MainWindow)
        self.statusbar.setObjectName("statusbar")
        ProjectOne_MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuTelevision.menuAction())

        self.retranslateUi(ProjectOne_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(ProjectOne_MainWindow)

    def retranslateUi(self, ProjectOne_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        ProjectOne_MainWindow.setWindowTitle(_translate("ProjectOne_MainWindow", "MainWindow"))
        self.PowerOn_label.setText(_translate("ProjectOne_MainWindow", "Power:"))
        self.PowerOn_btn.setText(_translate("ProjectOne_MainWindow", "On"))
        self.Channels_label.setText(_translate("ProjectOne_MainWindow", "Channels: "))
        self.ChannelDown_btn.setText(_translate("ProjectOne_MainWindow", "v"))
        self.ChannelUp_btn.setText(_translate("ProjectOne_MainWindow", "^"))
        self.Volume_label.setText(_translate("ProjectOne_MainWindow", "Volume: "))
        self.VoluemDown_btn.setText(_translate("ProjectOne_MainWindow", "-"))
        self.VolumeUp_btn.setText(_translate("ProjectOne_MainWindow", "+"))
        self.Mute_label.setText(_translate("ProjectOne_MainWindow", "Mute:"))
        self.MuteOn_btn.setText(_translate("ProjectOne_MainWindow", "On"))
        self.PowerOff_btn.setText(_translate("ProjectOne_MainWindow", "Off"))
        self.MuteOff_btn.setText(_translate("ProjectOne_MainWindow", "Off"))
        self.menuTelevision.setTitle(_translate("ProjectOne_MainWindow", "Television"))
