# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'one_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProjectOne_MainWindow(object):
    def setupUi(self, ProjectOne_MainWindow):
        ProjectOne_MainWindow.setObjectName("ProjectOne_MainWindow")
        ProjectOne_MainWindow.resize(250, 300)
        ProjectOne_MainWindow.setMinimumSize(QtCore.QSize(250, 300))
        ProjectOne_MainWindow.setMaximumSize(QtCore.QSize(700, 500))
        self.centralwidget = QtWidgets.QWidget(ProjectOne_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.power_label = QtWidgets.QLabel(self.centralwidget)
        self.power_label.setGeometry(QtCore.QRect(10, 10, 111, 16))
        self.power_label.setObjectName("power_label")
        self.power_button = QtWidgets.QPushButton(self.centralwidget)
        self.power_button.setGeometry(QtCore.QRect(10, 30, 71, 31))
        self.power_button.setObjectName("power_button")
        self.Channels_label = QtWidgets.QLabel(self.centralwidget)
        self.Channels_label.setGeometry(QtCore.QRect(170, 120, 71, 20))
        self.Channels_label.setObjectName("Channels_label")
        self.ChannelDown_btn = QtWidgets.QPushButton(self.centralwidget)
        self.ChannelDown_btn.setGeometry(QtCore.QRect(170, 160, 71, 41))
        self.ChannelDown_btn.setObjectName("ChannelDown_btn")
        self.ChannelUp_btn = QtWidgets.QPushButton(self.centralwidget)
        self.ChannelUp_btn.setGeometry(QtCore.QRect(170, 70, 71, 41))
        self.ChannelUp_btn.setObjectName("ChannelUp_btn")
        self.Volume_label = QtWidgets.QLabel(self.centralwidget)
        self.Volume_label.setGeometry(QtCore.QRect(10, 120, 71, 16))
        self.Volume_label.setObjectName("Volume_label")
        self.VoluemDown_btn = QtWidgets.QPushButton(self.centralwidget)
        self.VoluemDown_btn.setGeometry(QtCore.QRect(10, 160, 71, 41))
        self.VoluemDown_btn.setObjectName("VoluemDown_btn")
        self.VolumeUp_btn = QtWidgets.QPushButton(self.centralwidget)
        self.VolumeUp_btn.setGeometry(QtCore.QRect(10, 70, 71, 41))
        self.VolumeUp_btn.setObjectName("VolumeUp_btn")
        self.Mute_label = QtWidgets.QLabel(self.centralwidget)
        self.Mute_label.setGeometry(QtCore.QRect(100, 100, 31, 16))
        self.Mute_label.setObjectName("Mute_label")
        self.Mute_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Mute_btn.setGeometry(QtCore.QRect(90, 120, 61, 31))
        self.Mute_btn.setObjectName("Mute_btn")
        ProjectOne_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ProjectOne_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 250, 24))
        self.menubar.setObjectName("menubar")
        self.menuTelevision = QtWidgets.QMenu(self.menubar)
        self.menuTelevision.setObjectName("menuTelevision")
        ProjectOne_MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ProjectOne_MainWindow)
        self.statusbar.setObjectName("statusbar")
        ProjectOne_MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuTelevision.menuAction())

        self.retranslateUi(ProjectOne_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(ProjectOne_MainWindow)

    def retranslateUi(self, ProjectOne_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        ProjectOne_MainWindow.setWindowTitle(_translate("ProjectOne_MainWindow", "MainWindow"))
        self.power_label.setText(_translate("ProjectOne_MainWindow", "Power"))
        self.power_button.setText(_translate("ProjectOne_MainWindow", "On / Off"))
        self.Channels_label.setText(_translate("ProjectOne_MainWindow", "Channels: "))
        self.ChannelDown_btn.setText(_translate("ProjectOne_MainWindow", "v"))
        self.ChannelUp_btn.setText(_translate("ProjectOne_MainWindow", "^"))
        self.Volume_label.setText(_translate("ProjectOne_MainWindow", "Volume: "))
        self.VoluemDown_btn.setText(_translate("ProjectOne_MainWindow", "-"))
        self.VolumeUp_btn.setText(_translate("ProjectOne_MainWindow", "+"))
        self.Mute_label.setText(_translate("ProjectOne_MainWindow", "Mute"))
        self.Mute_btn.setText(_translate("ProjectOne_MainWindow", "On / Off"))
        self.menuTelevision.setTitle(_translate("ProjectOne_MainWindow", "Television"))
