# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'One_View_Copy.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProjectOne_MainWindow(object):
    def setupUi(self, ProjectOne_MainWindow):
        ProjectOne_MainWindow.setObjectName("ProjectOne_MainWindow")
        ProjectOne_MainWindow.resize(599, 477)
        ProjectOne_MainWindow.setMinimumSize(QtCore.QSize(290, 295))
        ProjectOne_MainWindow.setMaximumSize(QtCore.QSize(700, 500))
        self.centralwidget = QtWidgets.QWidget(ProjectOne_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Power_label = QtWidgets.QLabel(self.centralwidget)
        self.Power_label.setGeometry(QtCore.QRect(240, 270, 91, 16))
        self.Power_label.setObjectName("Power_label")
        self.Power_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Power_btn.setGeometry(QtCore.QRect(220, 290, 81, 41))
        self.Power_btn.setObjectName("Power_btn")
        self.Channels_label = QtWidgets.QLabel(self.centralwidget)
        self.Channels_label.setGeometry(QtCore.QRect(420, 260, 81, 20))
        self.Channels_label.setObjectName("Channels_label")
        self.ChannelDown_btn = QtWidgets.QPushButton(self.centralwidget)
        self.ChannelDown_btn.setGeometry(QtCore.QRect(410, 360, 101, 41))
        self.ChannelDown_btn.setObjectName("ChannelDown_btn")
        self.ChannelUp_btn = QtWidgets.QPushButton(self.centralwidget)
        self.ChannelUp_btn.setGeometry(QtCore.QRect(410, 290, 101, 41))
        self.ChannelUp_btn.setObjectName("ChannelUp_btn")
        self.Volume_label = QtWidgets.QLabel(self.centralwidget)
        self.Volume_label.setGeometry(QtCore.QRect(40, 260, 71, 16))
        self.Volume_label.setObjectName("Volume_label")
        self.VoluemDown_btn = QtWidgets.QPushButton(self.centralwidget)
        self.VoluemDown_btn.setGeometry(QtCore.QRect(30, 360, 101, 41))
        self.VoluemDown_btn.setObjectName("VoluemDown_btn")
        self.VolumeUp_btn = QtWidgets.QPushButton(self.centralwidget)
        self.VolumeUp_btn.setGeometry(QtCore.QRect(30, 290, 101, 41))
        self.VolumeUp_btn.setObjectName("VolumeUp_btn")
        self.Mute_label = QtWidgets.QLabel(self.centralwidget)
        self.Mute_label.setGeometry(QtCore.QRect(240, 340, 91, 16))
        self.Mute_label.setObjectName("Mute_label")
        self.Mute_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Mute_btn.setGeometry(QtCore.QRect(220, 360, 81, 41))
        self.Mute_btn.setObjectName("Mute_btn")
        self.TV_screen = QtWidgets.QLabel(self.centralwidget)
        self.TV_screen.setGeometry(QtCore.QRect(30, 0, 551, 251))
        self.TV_screen.setText("")
        self.TV_screen.setPixmap(QtGui.QPixmap("imgs/black_screen.jpg"))
        self.TV_screen.setScaledContents(True)
        self.TV_screen.setObjectName("TV_screen")
        self.Volume_display = QtWidgets.QLabel(self.centralwidget)
        self.Volume_display.setGeometry(QtCore.QRect(40, 210, 31, 31))
        self.Volume_display.setText("")
        self.Volume_display.setPixmap(QtGui.QPixmap("imgs/mute.png"))
        self.Volume_display.setScaledContents(True)
        self.Volume_display.setObjectName("Volume_display")
        ProjectOne_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ProjectOne_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 599, 24))
        self.menubar.setObjectName("menubar")
        self.menuTelevision = QtWidgets.QMenu(self.menubar)
        self.menuTelevision.setObjectName("menuTelevision")
        ProjectOne_MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ProjectOne_MainWindow)
        self.statusbar.setObjectName("statusbar")
        ProjectOne_MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuTelevision.menuAction())

        self.retranslateUi(ProjectOne_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(ProjectOne_MainWindow)

    def retranslateUi(self, ProjectOne_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        ProjectOne_MainWindow.setWindowTitle(_translate("ProjectOne_MainWindow", "MainWindow"))
        self.Power_label.setText(_translate("ProjectOne_MainWindow", "Power"))
        self.Power_btn.setText(_translate("ProjectOne_MainWindow", "On / Off"))
        self.Channels_label.setText(_translate("ProjectOne_MainWindow", "Channel"))
        self.ChannelDown_btn.setText(_translate("ProjectOne_MainWindow", "-"))
        self.ChannelUp_btn.setText(_translate("ProjectOne_MainWindow", "+"))
        self.Volume_label.setText(_translate("ProjectOne_MainWindow", "Volume"))
        self.VoluemDown_btn.setText(_translate("ProjectOne_MainWindow", "-"))
        self.VolumeUp_btn.setText(_translate("ProjectOne_MainWindow", "+"))
        self.Mute_label.setText(_translate("ProjectOne_MainWindow", "Mute"))
        self.Mute_btn.setText(_translate("ProjectOne_MainWindow", "On / Off"))
        self.menuTelevision.setTitle(_translate("ProjectOne_MainWindow", "Television"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProjectOne_MainWindow = QtWidgets.QMainWindow()
    ui = Ui_ProjectOne_MainWindow()
    ui.setupUi(ProjectOne_MainWindow)
    ProjectOne_MainWindow.show()
    sys.exit(app.exec_())
